apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    # prometheus-operated is the service created by kube-prometheus-stack in the same namespace
    url: http://prometheus-operated:9090
    isDefault: true
    editable: true

  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://iot-agent-loki:3100
    editable: true
