grafana:
  adminPassword: admin
  service:
    type: ClusterIP
  defaultDashboardsTimezone: Europe/Warsaw

prometheus:
  prometheusSpec:
    retention: 14d
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorNamespaceSelector: {}

alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 5Gi
