image:
  registry: docker.io
  repository: grafana/promtail
  tag: 3.4.2
  pullPolicy: IfNotPresent

config:
  clients:
    - url: http://iot-agent-loki-gateway.iotag-monitoring.svc.cluster.local/loki/api/v1/push

extraScrapeConfigs: |
  - job_name: kubernetes-pods
    kubernetes_sd_configs:
      - role: pod
